name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.BASTION_IP }} >> ~/.ssh/known_hosts

    - name: Set BASTION_IP env
      run: echo "BASTION_IP=${{ secrets.BASTION_IP }}" >> $GITHUB_ENV

    - name: Generate Ansible inventory
      run: python ansible/generate_inventory.py
      env:
        BASTION_IP: ${{ secrets.BASTION_IP }}

    - name: Check SSH connection
      run: ssh -o BatchMode=yes -o StrictHostKeyChecking=no debian@${{ secrets.BASTION_IP }} 'echo SSH connection OK'

    - name: Run Ansible playbook to configure bastion
      run: ansible-playbook -i ansible/inventory.ini ansible/setup_kubectl.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'

    - name: Healthcheck - Verify Nginx service
      run: |
        echo "Waiting for Nginx service to be ready..."
        ssh debian@${{ secrets.BASTION_IP }} "
          export KUBECONFIG=/home/debian/kubeconfig.yml
          kubectl wait --for=condition=available deployment/nginx-deployment --timeout=60s
          kubectl get svc nginx-service
        "
